//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyFeed {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabyFeed.AppResx", typeof(AppResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BabyFeed for Windows Phone v1.0
        ///
        ///Find us at www.hlimasoft.com
        ///
        ///Illustrations by Pedro Grego
        ///Graphics Design by João Pinto
        ///Programming by Hugo Lima
        ///
        ///BabyFeed developer denies of any and all liability for any damages that arise out of using this software application, including the failure to meet feeding or medicine schedules..
        /// </summary>
        public static string about_text {
            get {
                return ResourceManager.GetString("about_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s).
        /// </summary>
        public static string agedays {
            get {
                return ResourceManager.GetString("agedays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} month(s).
        /// </summary>
        public static string agemonths {
            get {
                return ResourceManager.GetString("agemonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} week(s) and {1} day(s).
        /// </summary>
        public static string ageweeksdays {
            get {
                return ResourceManager.GetString("ageweeksdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year(s).
        /// </summary>
        public static string ageyears {
            get {
                return ResourceManager.GetString("ageyears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year(s) and {1} month(s).
        /// </summary>
        public static string ageyearsmonths {
            get {
                return ResourceManager.GetString("ageyearsmonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alarms.
        /// </summary>
        public static string alarms {
            get {
                return ResourceManager.GetString("alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baby feed.
        /// </summary>
        public static string apptitle {
            get {
                return ResourceManager.GetString("apptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my babies.
        /// </summary>
        public static string babies {
            get {
                return ResourceManager.GetString("babies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baby.
        /// </summary>
        public static string baby {
            get {
                return ResourceManager.GetString("baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthday.
        /// </summary>
        public static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boy.
        /// </summary>
        public static string boy {
            get {
                return ResourceManager.GetString("boy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to girl.
        /// </summary>
        public static string girl {
            get {
                return ResourceManager.GetString("girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w:{0}, h:{1}, c:{2}.
        /// </summary>
        public static string measures {
            get {
                return ResourceManager.GetString("measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes between feeds.
        /// </summary>
        public static string minutes_between_feeds {
            get {
                return ResourceManager.GetString("minutes_between_feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new baby.
        /// </summary>
        public static string newbaby {
            get {
                return ResourceManager.GetString("newbaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer alarms.
        /// </summary>
        public static string timer_alarms {
            get {
                return ResourceManager.GetString("timer_alarms", resourceCulture);
            }
        }
    }
}
